-- SOLO para una base nueva. Se detiene si monarca ya contiene tablas.
-- La instalación existente de Supabase no necesita recrearse.
BEGIN;
DO $$ BEGIN
 IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='monarca') THEN
   RAISE EXCEPTION 'monarca ya contiene tablas. No ejecutar este esquema sobre la base existente.';
 END IF;
END $$;
CREATE SCHEMA IF NOT EXISTS monarca;
CREATE TABLE monarca.roles (
 id_rol bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre varchar(30) NOT NULL UNIQUE,
 descripcion varchar(150), activo boolean NOT NULL DEFAULT true
);
CREATE TABLE monarca.usuarios (
 id_usuario bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_rol bigint NOT NULL REFERENCES monarca.roles,
 nombres varchar(100) NOT NULL, apellidos varchar(100) NOT NULL, correo varchar(150) NOT NULL,
 password_hash varchar(255) NOT NULL, telefono varchar(20), tipo_documento varchar(20), numero_documento varchar(20),
 activo boolean NOT NULL DEFAULT true, fecha_creacion timestamptz NOT NULL DEFAULT now(), fecha_actualizacion timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX usuarios_correo_normalizado ON monarca.usuarios(lower(correo));
CREATE TABLE monarca.categorias (
 id_categoria bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre varchar(100) NOT NULL UNIQUE,
 slug varchar(120) NOT NULL UNIQUE, descripcion varchar(300), activo boolean NOT NULL DEFAULT true, fecha_creacion timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE monarca.productos (
 id_producto bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_categoria bigint NOT NULL REFERENCES monarca.categorias,
 nombre varchar(150) NOT NULL, slug varchar(180) NOT NULL UNIQUE, descripcion text, marca varchar(100), precio_base numeric(10,2) NOT NULL CHECK(precio_base>=0),
 activo boolean NOT NULL DEFAULT true, destacado boolean NOT NULL DEFAULT false, fecha_creacion timestamptz NOT NULL DEFAULT now(), fecha_actualizacion timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE monarca.variantes_producto (
 id_variante bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_producto bigint NOT NULL REFERENCES monarca.productos,
 sku varchar(80) NOT NULL UNIQUE, talla varchar(20) NOT NULL, color varchar(50) NOT NULL, color_hex varchar(10),
 precio numeric(10,2) NOT NULL CHECK(precio>=0), stock integer NOT NULL DEFAULT 0 CHECK(stock>=0), stock_minimo integer NOT NULL DEFAULT 0 CHECK(stock_minimo>=0),
 activo boolean NOT NULL DEFAULT true, fecha_creacion timestamptz NOT NULL DEFAULT now(), fecha_actualizacion timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT uk_producto_variante UNIQUE(id_producto,talla,color)
);
CREATE TABLE monarca.imagenes_producto (
 id_imagen bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_producto bigint NOT NULL REFERENCES monarca.productos,
 id_variante bigint REFERENCES monarca.variantes_producto, url text NOT NULL, texto_alternativo varchar(200), principal boolean NOT NULL DEFAULT false,
 orden integer NOT NULL DEFAULT 0, fecha_creacion timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE monarca.metodos_pago (
 id_metodo_pago bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo varchar(30) NOT NULL UNIQUE,
 nombre varchar(100) NOT NULL UNIQUE, descripcion varchar(250), requiere_comprobante boolean NOT NULL DEFAULT false, activo boolean NOT NULL DEFAULT true
);
CREATE TABLE monarca.pedidos (
 id_pedido bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo_pedido varchar(40) UNIQUE, id_usuario bigint NOT NULL REFERENCES monarca.usuarios,
 estado varchar(30) NOT NULL DEFAULT 'PENDIENTE_PAGO' CHECK(estado IN ('PENDIENTE_PAGO','PAGADO','ENVIADO','ENTREGADO','CANCELADO')),
 subtotal numeric(10,2) NOT NULL, descuento numeric(10,2) NOT NULL DEFAULT 0, costo_envio numeric(10,2) NOT NULL DEFAULT 0,
 total numeric(10,2) NOT NULL, observacion varchar(500), fecha_pedido timestamptz NOT NULL DEFAULT now(), fecha_actualizacion timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE monarca.detalles_pedido (
 id_detalle bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_pedido bigint NOT NULL REFERENCES monarca.pedidos,
 id_variante bigint NOT NULL REFERENCES monarca.variantes_producto, cantidad integer NOT NULL CHECK(cantidad>0),
 precio_unitario numeric(10,2) NOT NULL, subtotal numeric(10,2) NOT NULL, nombre_producto varchar(150) NOT NULL,
 sku varchar(80) NOT NULL, talla varchar(20), color varchar(50)
);
CREATE TABLE monarca.pagos (
 id_pago bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_pedido bigint NOT NULL REFERENCES monarca.pedidos,
 id_metodo_pago bigint NOT NULL REFERENCES monarca.metodos_pago, monto numeric(10,2) NOT NULL,
 estado varchar(30) NOT NULL DEFAULT 'PENDIENTE' CHECK(estado IN ('PENDIENTE','EN_REVISION','PAGADO','RECHAZADO','CANCELADO','REEMBOLSADO')),
 numero_operacion varchar(100), comprobante_url text, proveedor_pago varchar(100), referencia_externa varchar(150), observacion varchar(300),
 fecha_creacion timestamptz NOT NULL DEFAULT now(), fecha_pago timestamptz, fecha_confirmacion timestamptz
);
CREATE INDEX pedidos_usuario ON monarca.pedidos(id_usuario,id_pedido);
CREATE INDEX detalles_pedido_pedido ON monarca.detalles_pedido(id_pedido);
CREATE INDEX pagos_pedido ON monarca.pagos(id_pedido);
CREATE INDEX variantes_producto_producto ON monarca.variantes_producto(id_producto);
CREATE INDEX imagenes_producto_producto ON monarca.imagenes_producto(id_producto);
COMMIT;
